version: '3.7'

services:
  helix-honeypot-ad:
   build: ./
   ports:
     - "8000:8000"
   entrypoint: [/helix-honeypot, -mode=ad]
   volumes:
     - /dev/random:/dev/random
  helix-honeypot:
    build: ./
    ports:
      - "80:8000"
