version: '3.7'

services:
  helix-honeypot-ad:
   image: helixhoneypot/helixhoneypot
   ports:
     - "8000:8000"
   entrypoint: [/helix-honeypot, -mode=ad]
  helix-honeypot:
    image: helixhoneypot/helixhoneypot
    ports:
      - "80:8000"