version: '3.7'

services:
  helix-honeypot-ad:
   build: ./
   ports:
     - "8000:80"
   entrypoint: [/helix-honeypot, -mode=ad]
   volumes:
     - /dev/urandom:/dev/urandom
  helix-honeypot:
    build: ./
    ports:
      - "8111:80"
