name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 14 * * 1'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the image latest
      run: docker build . --file Dockerfile --tag helixhoneypot/helixhoneypot:latest
    - name: Docker Push Latest
      run: docker push helixhoneypot/helixhoneypot:latest
